{"version":20180619,"tag":"872093737","params":"action\narg\nevt","when_created":1658089110.924,"parent_id":"34e4d875","props":[],"created_by":"stipan","items":{"2":{"type":"branch","branchId":0,"one":"3","id":"2"},"1":{"type":"end","id":"1"},"3":{"type":"action","text":"try {\n    action(arg, evt)\n} catch (ex) {\n    console.error(\n        \"User event caused an error\",\n        ex\n    )\n}","one":"1","id":"3"}},"keywords":{"scenario":false,"async":false,"export":false,"function":true,"algoprop":false},"when_updated":1658089154.3265,"updated_by":"stipan","type":"drakon","name":"actionWrapper","language":"LANG_S42"}